### PR TITLE
fix openmp build and reformat with isort&black

### PR DESCRIPTION
**Pull request by synodriver**
- With proper configuration of openmp, cython's prange can benefit from multi core CPU, other wise it will fallback to a single thread loop, see [cython's document](https://docs.cython.org/en/stable/src/userguide/parallelism.html#compiling)
- Reformat with isort and black which follows PEP8

### CODE REVIEW

**Comment by synodriver** [comment]
居然是2格缩进 ~~isort 和 black自动就改了~~

**Comment by CjangCjengh** [comment]
Sorry, but I don't want to change my format... Could you push your fix separately?

**Comment by synodriver** [comment]
revert就行了（等下我改改

**Comment by CjangCjengh** [comment]
感谢

**Pull request merged**
